### ISSUE TITLE
Warning about peer dependency with react 17

### ISSUE THREAD

**Issue by pixelass** [bring-shrubbery/use-cookie-consent#6]
**Describe the bug**
When installing in a react 17.x project there are warnings about the peer dependencies

**To Reproduce**
1. Create a project with react 17.x
2. add this library
3. install the dependencies
4. See warning

**Expected behavior**
This library should not complain about react 17.x

```
20:03:37.385 | warning " > use-cookie-consent@0.1.12" has incorrect peer dependency "react@^16.9".
20:03:37.386 | warning " > use-cookie-consent@0.1.12" has incorrect peer dependency "react-dom@^16.9".
```

**Versions**

 use-cookie-consent: v0.1.12

**Comment by bring-shrubbery** [comment]
Thanks for submitting the issue! The above PR should solve the problem and release v0.1.13 should have these changes reflected.
